// This file was autogenerated by Mustache. DO NOT CHANGE.
import Sailboat

extension Element {

    public func onClick(_ completion: @escaping () -> Void) -> Self {
        var copy = self

        copy.events["click"] = { _ in
            SailorGlobal.manager.startEvent()
            completion()
            SailorGlobal.manager.endEvent()
        }

        return copy
    }

}
