// This file was autogenerated by Mustache. DO NOT CHANGE.
import Sailboat

extension Element {

    public func onKeyUp(_ completion: @escaping (String) -> Void) -> Self {
        var copy = self

        copy.events["keyup"] = { eventResult in
            if case let EventResult.string(value) = eventResult {
                completion(value)
            }
        }

        return copy
    }

}
